[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_chest = "CKBZ7U5CWFnUohedMMRhSiK1xzEbcC3j6G9dxsbqmtJW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "solana-chest-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
